# 关键字
keywords: Elijah博客,Elijah Blog,博客,Elijah,Linux,Kubernetes,Docker,DevOps
# 作者
author: Elijah
# 网站左侧描述
description: 描述信息
# 如需修改icon,请替换 source/images/favicon.ico 文件
avatar: /images/favicon.png
beian: 冀ICP备xxxxxxxxxx号
# 版权
copyright: 2020 - 2025


# 社交账号
github: https://github.com/sreok
mail: mailto:admin@vsoul.cn
zhihu: 
qq: 
wechat: 
rss: true